# Generated by Django 5.1 on 2024-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_hrrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketing_name", models.CharField(max_length=255, null=True)),
                ("latin_name", models.CharField(max_length=255)),
                ("dose", models.IntegerField()),
                ("dose_unit", models.CharField(max_length=64)),
                ("type", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "Medicines",
            },
        ),
    ]
