# Generated by Django 5.1 on 2024-10-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="type",
            field=models.CharField(
                choices=[("preventive", "Preventive"), ("acute", "Acute")],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="DayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.IntegerField()),
                ("date", models.DateField()),
                ("notes", models.CharField(max_length=255, null=True)),
                (
                    "hr_records",
                    models.ManyToManyField(related_name="day_logs", to="core.hrrecord"),
                ),
                (
                    "medicines",
                    models.ManyToManyField(related_name="day_logs", to="core.medicine"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DayLogs",
                "ordering": ["-date"],
            },
        ),
    ]
