# Generated by Django 5.1 on 2024-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_medicine_type_daylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daylog",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="marketing_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
