# Generated by Django 5.1 on 2024-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_daylog_notes_alter_medicine_marketing_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daylog",
            name="hr_records",
            field=models.ManyToManyField(
                blank=True, related_name="day_logs", to="core.hrrecord"
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="medicines",
            field=models.ManyToManyField(
                blank=True, related_name="day_logs", to="core.medicine"
            ),
        ),
    ]
