# Generated by Django 5.1 on 2025-02-13 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_visit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="planned",
        ),
    ]
