version: "3.9"

services:
  postgres:
    restart: unless-stopped
    image: postgres:15.2
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_HOST: $DB_HOST
      POSTGRES_PORT: $DB_PORT
      PGUSER: $DB_USER
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  medlog:
    restart: unless-stopped
    container_name: medlog_backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./medlog:/medlog
    entrypoint: /docker-entrypoint.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
